[
  { "id": "1", "name": "Vodka", "type": "Vodka", "alcoholic": "Yes" },
  { "id": "2", "name": "Gin", "type": "Gin", "alcoholic": "Yes" },
  { "id": "3", "name": "Rum", "type": "Rum", "alcoholic": "Yes" },
  { "id": "4", "name": "Tequila", "type": "Spirit", "alcoholic": "Yes" },
  { "id": "5", "name": "Scotch", "type": "Whisky", "alcoholic": "Yes" },
  { "id": "6", "name": "Absolut Kurant", "type": "Vodka", "alcoholic": "Yes" },
  { "id": "7", "name": "Absolut Peppar", "type": "Vodka", "alcoholic": "Yes" },
  { "id": "8", "name": "Absolut Vodka", "type": "Vodka", "alcoholic": "Yes" },
  { "id": "9", "name": "Advocaat", "type": "Spirit", "alcoholic": "Yes" },
  { "id": "10", "name": "Aejo Rum", "type": "Rum", "alcoholic": "Yes" },
  { "id": "11", "name": "Aftershock", "type": "Spirit", "alcoholic": "Yes" },
  { "id": "12", "name": "Agave Syrup", "type": "Syrup", "alcoholic": "No" },
  { "id": "13", "name": "Ale", "type": "Beer", "alcoholic": "Yes" },
  { "id": "14", "name": "Allspice", "type": null, "alcoholic": "No" },
  { "id": "15", "name": "Almond Extract", "type": null, "alcoholic": "No" },
  { "id": "16", "name": "Almond Flavoring", "type": null, "alcoholic": "No" },
  { "id": "17", "name": "Almond", "type": null, "alcoholic": "No" },
  { "id": "18", "name": "Amaretto", "type": "Liqueur", "alcoholic": "Yes" },
  { "id": "19", "name": "Angelica Root", "type": null, "alcoholic": "No" },
  { "id": "20", "name": "Angostura Bitters", "type": "Bitter", "alcoholic": "No" },
  { "id": "21", "name": "Anis", "type": null, "alcoholic": "No" },
  { "id": "22", "name": "Anise", "type": null, "alcoholic": "No" },
  { "id": "23", "name": "Anisette", "type": null, "alcoholic": "No" },
  { "id": "24", "name": "Aperol", "type": "Liqueur", "alcoholic": "Yes" },
  { "id": "25", "name": "Apfelkorn", "type": null, "alcoholic": "Yes" },
  { "id": "26", "name": "Apple Brandy", "type": "Brandy", "alcoholic": "Yes" },
  { "id": "27", "name": "Apple Cider", "type": "Cider", "alcoholic": "Yes" },
  { "id": "28", "name": "Apple Juice", "type": null, "alcoholic": null },
  { "id": "29", "name": "Apple Schnapps", "type": "Liquor", "alcoholic": "Yes" },
  { "id": "30", "name": "Apple", "type": null, "alcoholic": null },
  { "id": "31", "name": "Applejack", "type": "Beverage", "alcoholic": "Yes" },
  { "id": "32", "name": "Apricot Brandy", "type": "Brandy", "alcoholic": "Yes" },
  { "id": "33", "name": "Apricot Nectar", "type": null, "alcoholic": null },
  { "id": "34", "name": "Apricot", "type": null, "alcoholic": null },
  { "id": "35", "name": "Aquavit", "type": null, "alcoholic": null },
  { "id": "36", "name": "Asafoetida", "type": null, "alcoholic": null },
  { "id": "37", "name": "Añejo Rum", "type": "Rum", "alcoholic": "Yes" },
  { "id": "39", "name": "Bacardi Limon", "type": "Rum", "alcoholic": "Yes" },
  { "id": "40", "name": "Bacardi", "type": "Rum", "alcoholic": "Yes" },
  { "id": "43", "name": "Baileys Irish Cream", "type": "Liqueur", "alcoholic": "Yes" },
  { "id": "44", "name": "Banana Liqueur", "type": "Liqueur", "alcoholic": "Yes" },
  { "id": "45", "name": "Banana Rum", "type": "Rum", "alcoholic": "Yes" },
  { "id": "46", "name": "Banana Syrup", "type": null, "alcoholic": null },
  { "id": "47", "name": "Banana", "type": null, "alcoholic": null },
  { "id": "48", "name": "Barenjager", "type": null, "alcoholic": null },
  { "id": "49", "name": "Basil", "type": null, "alcoholic": null },
  { "id": "51", "name": "Beef Stock", "type": null, "alcoholic": null },
  { "id": "52", "name": "Beer", "type": "Beer", "alcoholic": "Yes" },
  { "id": "53", "name": "Benedictine", "type": null, "alcoholic": null },
  { "id": "54", "name": "Berries", "type": null, "alcoholic": null },
  { "id": "55", "name": "Bitter lemon", "type": null, "alcoholic": null },
  { "id": "56", "name": "Bitters", "type": null, "alcoholic": null },
  { "id": "57", "name": "Black Pepper", "type": null, "alcoholic": null },
  { "id": "58", "name": "Black Rum", "type": "Rum", "alcoholic": "Yes" },
  { "id": "59", "name": "Black Sambuca", "type": "Sambuca", "alcoholic": "Yes" },
  { "id": "60", "name": "Blackberries", "type": null, "alcoholic": null },
  { "id": "61", "name": "Blackberry Brandy", "type": "Brandy", "alcoholic": "Yes" },
  { "id": "62", "name": "Blackberry Schnapps", "type": "Liquor", "alcoholic": null },
  { "id": "63", "name": "Blackcurrant Cordial", "type": null, "alcoholic": null },
  { "id": "64", "name": "Blackcurrant Schnapps", "type": "Liquor", "alcoholic": "Yes" },
  { "id": "65", "name": "Blackcurrant Squash", "type": null, "alcoholic": null },
  { "id": "66", "name": "Blended Whiskey", "type": "Whiskey", "alcoholic": "Yes" },
  { "id": "67", "name": "Blue Curacao", "type": "Liqueur", "alcoholic": "Yes" },
  { "id": "68", "name": "Blue Maui", "type": null, "alcoholic": null },
  { "id": "69", "name": "Blueberries", "type": null, "alcoholic": null },
  { "id": "70", "name": "Blueberry Schnapps", "type": "Liquor", "alcoholic": "Yes" },
  { "id": "71", "name": "Bourbon", "type": "Whiskey", "alcoholic": "Yes" },
  { "id": "74", "name": "Brandy", "type": "Spirit", "alcoholic": "Yes" },
  { "id": "77", "name": "Brown Sugar", "type": null, "alcoholic": null },
  { "id": "79", "name": "Butter", "type": null, "alcoholic": null },
  { "id": "80", "name": "Butterscotch Schnapps", "type": "Liquor", "alcoholic": "Yes" },
  { "id": "81", "name": "Cachaca", "type": "Spirit", "alcoholic": "Yes" },
  { "id": "82", "name": "Calvados", "type": null, "alcoholic": null },
  { "id": "83", "name": "Campari", "type": null, "alcoholic": null },
  { "id": "84", "name": "Canadian Whisky", "type": "Whiskey", "alcoholic": "Yes" },
  { "id": "85", "name": "Candy", "type": null, "alcoholic": null },
  { "id": "86", "name": "Cantaloupe", "type": null, "alcoholic": null },
  { "id": "87", "name": "Caramel Coloring", "type": null, "alcoholic": null },
  { "id": "88", "name": "Carbonated Soft Drink", "type": null, "alcoholic": null },
  { "id": "89", "name": "Carbonated Water", "type": null, "alcoholic": null },
  { "id": "90", "name": "Cardamom", "type": null, "alcoholic": null },
  { "id": "93", "name": "Cayenne Pepper", "type": null, "alcoholic": null },
  { "id": "94", "name": "Celery Salt", "type": null, "alcoholic": null },
  { "id": "95", "name": "Celery", "type": null, "alcoholic": null },
  { "id": "96", "name": "Chambord Raspberry Liqueur", "type": "Liqueur", "alcoholic": "Yes" },
  { "id": "97", "name": "Champagne", "type": "Wine", "alcoholic": "Yes" },
  { "id": "99", "name": "Cherries", "type": null, "alcoholic": null },
  { "id": "100", "name": "Cherry Brandy", "type": null, "alcoholic": null },
  { "id": "101", "name": "Cherry Cola", "type": null, "alcoholic": null },
  { "id": "102", "name": "Cherry Grenadine", "type": null, "alcoholic": null },
  { "id": "103", "name": "Cherry Heering", "type": null, "alcoholic": null },
  { "id": "104", "name": "Cherry Juice", "type": null, "alcoholic": null },
  { "id": "105", "name": "Cherry Liqueur", "type": "Liqueur", "alcoholic": "Yes" },
  { "id": "106", "name": "Cherry", "type": null, "alcoholic": null },
  { "id": "112", "name": "Chocolate Ice-cream", "type": null, "alcoholic": null },
  { "id": "113", "name": "Chocolate Liqueur", "type": "Liqueur", "alcoholic": "Yes" },
  { "id": "114", "name": "Chocolate Milk", "type": null, "alcoholic": null },
  { "id": "115", "name": "Chocolate Syrup", "type": null, "alcoholic": null },
  { "id": "116", "name": "Chocolate", "type": null, "alcoholic": null },
  { "id": "120", "name": "Cider", "type": "Cider", "alcoholic": "Yes" },
  { "id": "121", "name": "Cinnamon Schnapps", "type": "Liquor", "alcoholic": null },
  { "id": "122", "name": "Cinnamon", "type": null, "alcoholic": null },
  { "id": "123", "name": "Citrus Vodka", "type": "Vodka", "alcoholic": "Yes" },
  { "id": "124", "name": "Clamato Juice", "type": null, "alcoholic": null },
  { "id": "126", "name": "Cloves", "type": null, "alcoholic": null },
  { "id": "127", "name": "Club Soda", "type": null, "alcoholic": null },
  { "id": "128", "name": "Coca-Cola", "type": "Soft Drink", "alcoholic": null },
  { "id": "130", "name": "Cocktail Onion", "type": null, "alcoholic": null },
  { "id": "131", "name": "Cocoa Powder", "type": null, "alcoholic": null },
  { "id": "132", "name": "Coconut Cream", "type": null, "alcoholic": null },
  { "id": "133", "name": "Coconut Liqueur", "type": "Liqueur", "alcoholic": "Yes" },
  { "id": "134", "name": "Coconut Milk", "type": null, "alcoholic": null },
  { "id": "135", "name": "Coconut Rum", "type": "Rum", "alcoholic": "Yes" },
  { "id": "136", "name": "Coconut Syrup", "type": null, "alcoholic": null },
  { "id": "137", "name": "Coffee Brandy", "type": "Brandy", "alcoholic": "Yes" },
  { "id": "138", "name": "Coffee Liqueur", "type": "Liqueur", "alcoholic": "Yes" },
  { "id": "139", "name": "Coffee", "type": "Coffee", "alcoholic": null },
  { "id": "141", "name": "Cognac", "type": "Brandy", "alcoholic": "Yes" },
  { "id": "142", "name": "Cointreau", "type": "Liqueur", "alcoholic": "Yes" },
  { "id": "143", "name": "Cola", "type": "Soft Drink", "alcoholic": "No" },
  { "id": "144", "name": "Cold Water", "type": null, "alcoholic": null },
  { "id": "145", "name": "Condensed Milk", "type": null, "alcoholic": null },
  { "id": "147", "name": "Coriander", "type": null, "alcoholic": null },
  { "id": "149", "name": "Corn Syrup", "type": null, "alcoholic": null },
  { "id": "151", "name": "Cornstarch", "type": null, "alcoholic": null },
  { "id": "152", "name": "Corona", "type": "Beer", "alcoholic": "Yes" },
  { "id": "154", "name": "Cranberries", "type": null, "alcoholic": null },
  { "id": "155", "name": "Cranberry Juice", "type": "Juice", "alcoholic": null },
  { "id": "156", "name": "Cranberry Liqueur", "type": "Liqueur", "alcoholic": "Yes" },
  { "id": "157", "name": "Cranberry Vodka", "type": "Vodka", "alcoholic": "Yes" },
  { "id": "158", "name": "Cream of Coconut", "type": null, "alcoholic": null },
  { "id": "159", "name": "Cream Sherry", "type": "Sherry", "alcoholic": "Yes" },
  { "id": "160", "name": "Cream Soda", "type": null, "alcoholic": null },
  { "id": "161", "name": "Cream", "type": null, "alcoholic": null },
  { "id": "162", "name": "Creme De Almond", "type": null, "alcoholic": null },
  { "id": "163", "name": "Creme De Banane", "type": null, "alcoholic": null },
  { "id": "164", "name": "Creme De Cacao", "type": null, "alcoholic": null },
  { "id": "165", "name": "Creme De Cassis", "type": "Liqueur", "alcoholic": "Yes" },
  { "id": "166", "name": "Creme De Noyaux", "type": null, "alcoholic": null },
  { "id": "167", "name": "Creme Fraiche", "type": null, "alcoholic": null },
  { "id": "168", "name": "Crown Royal", "type": null, "alcoholic": null },
  { "id": "169", "name": "Crystal Light", "type": null, "alcoholic": null },
  { "id": "171", "name": "Cucumber", "type": null, "alcoholic": null },
  { "id": "172", "name": "Cumin Powder", "type": null, "alcoholic": null },
  { "id": "173", "name": "Cumin Seed", "type": null, "alcoholic": null },
  { "id": "174", "name": "Curacao", "type": null, "alcoholic": null },
  { "id": "175", "name": "Cynar", "type": null, "alcoholic": null },
  { "id": "176", "name": "Daiquiri Mix", "type": null, "alcoholic": null },
  { "id": "177", "name": "Dark Chocolate", "type": null, "alcoholic": null },
  { "id": "178", "name": "Dark Creme De Cacao", "type": null, "alcoholic": null },
  { "id": "179", "name": "Dark Rum", "type": "Rum", "alcoholic": "Yes" },
  { "id": "180", "name": "Dark Soy Sauce", "type": null, "alcoholic": null },
  { "id": "181", "name": "Demerara Sugar", "type": null, "alcoholic": null },
  { "id": "186", "name": "Dr. Pepper", "type": "Soft Drink", "alcoholic": null },
  { "id": "187", "name": "Drambuie", "type": "Liqueur", "alcoholic": "Yes" },
  { "id": "188", "name": "Dried Oregano", "type": null, "alcoholic": null },
  { "id": "189", "name": "Dry Vermouth", "type": "Fortified Wine", "alcoholic": "Yes" },
  { "id": "190", "name": "Dubonnet Blanc", "type": null, "alcoholic": null },
  { "id": "191", "name": "Dubonnet Rouge", "type": null, "alcoholic": null },
  { "id": "192", "name": "Egg White", "type": null, "alcoholic": null },
  { "id": "193", "name": "Egg Yolk", "type": null, "alcoholic": null },
  { "id": "194", "name": "Egg", "type": null, "alcoholic": null },
  { "id": "195", "name": "Eggnog", "type": null, "alcoholic": null },
  { "id": "199", "name": "Erin Cream", "type": null, "alcoholic": null },
  { "id": "200", "name": "Espresso", "type": null, "alcoholic": null },
  { "id": "201", "name": "Everclear", "type": null, "alcoholic": null },
  { "id": "203", "name": "Fanta", "type": null, "alcoholic": null },
  { "id": "205", "name": "Fennel Seeds", "type": null, "alcoholic": null },
  { "id": "207", "name": "Firewater", "type": null, "alcoholic": null },
  { "id": "208", "name": "Flaked Almonds", "type": null, "alcoholic": null },
  { "id": "210", "name": "Food Coloring", "type": null, "alcoholic": null },
  { "id": "211", "name": "Forbidden Fruit", "type": null, "alcoholic": null },
  { "id": "212", "name": "Frangelico", "type": null, "alcoholic": null },
  { "id": "215", "name": "Fresca", "type": null, "alcoholic": null },
  { "id": "216", "name": "Fresh Basil", "type": "Spice", "alcoholic": null },
  { "id": "217", "name": "Fresh Lemon Juice", "type": "Juice", "alcoholic": null },
  { "id": "220", "name": "Fruit Juice", "type": "Juice", "alcoholic": null },
  { "id": "221", "name": "Fruit Punch", "type": "Juice", "alcoholic": null },
  { "id": "222", "name": "Fruit", "type": "Fruit", "alcoholic": null },
  { "id": "223", "name": "Galliano", "type": "Liqueur", "alcoholic": "Yes" },
  { "id": "224", "name": "Garlic Sauce", "type": "Sauce", "alcoholic": null },
  { "id": "226", "name": "Gatorade", "type": "Soft Drink", "alcoholic": null },
  { "id": "228", "name": "Ginger Ale", "type": "Soft Drink", "alcoholic": null },
  { "id": "229", "name": "Ginger Beer", "type": "Soft Drink", "alcoholic": null },
  { "id": "230", "name": "Ginger", "type": null, "alcoholic": null },
  { "id": "231", "name": "Glycerine", "type": null, "alcoholic": null },
  { "id": "232", "name": "Godiva Liqueur", "type": "Liqueur", "alcoholic": "Yes" },
  { "id": "233", "name": "Gold rum", "type": "Rum", "alcoholic": "Yes" },
  { "id": "234", "name": "Gold Tequila", "type": "Tequila", "alcoholic": "Yes" },
  { "id": "235", "name": "Goldschlager", "type": "Schnapps", "alcoholic": "Yes" },
  { "id": "237", "name": "Grain Alcohol", "type": null, "alcoholic": null },
  { "id": "238", "name": "Grand Marnier", "type": "Liqueur", "alcoholic": "Yes" },
  { "id": "239", "name": "Granulated Sugar", "type": null, "alcoholic": null },
  { "id": "240", "name": "Grape juice", "type": null, "alcoholic": null },
  { "id": "241", "name": "Grape soda", "type": null, "alcoholic": null },
  { "id": "242", "name": "Grapefruit Juice", "type": null, "alcoholic": null },
  { "id": "243", "name": "Grapes", "type": null, "alcoholic": null },
  { "id": "245", "name": "Green Chartreuse", "type": null, "alcoholic": null },
  { "id": "246", "name": "Green Creme de Menthe", "type": "Liqueur", "alcoholic": "Yes" },
  { "id": "247", "name": "Green Ginger Wine", "type": null, "alcoholic": null },
  { "id": "248", "name": "Green Olives", "type": null, "alcoholic": null },
  { "id": "250", "name": "Grenadine", "type": "Syrup", "alcoholic": null },
  { "id": "252", "name": "Ground Ginger", "type": null, "alcoholic": null },
  { "id": "253", "name": "Guava juice", "type": null, "alcoholic": null },
  { "id": "254", "name": "Guinness stout", "type": "Stout", "alcoholic": "Yes" },
  { "id": "255", "name": "Guinness", "type": "Stout", "alcoholic": "Yes" },
  { "id": "256", "name": "Half-and-half", "type": "Soft Drink", "alcoholic": null },
  { "id": "257", "name": "Hawaiian punch", "type": null, "alcoholic": null },
  { "id": "258", "name": "Hazelnut liqueur", "type": null, "alcoholic": null },
  { "id": "259", "name": "Heavy cream", "type": "Cream", "alcoholic": null },
  { "id": "260", "name": "Honey", "type": null, "alcoholic": null },
  { "id": "261", "name": "Hooch", "type": null, "alcoholic": null },
  { "id": "264", "name": "Hot Chocolate", "type": null, "alcoholic": null },
  { "id": "265", "name": "Hot Damn", "type": null, "alcoholic": null },
  { "id": "266", "name": "Hot Sauce", "type": null, "alcoholic": null },
  { "id": "268", "name": "Hpnotiq", "type": null, "alcoholic": null },
  { "id": "269", "name": "Ice-Cream", "type": null, "alcoholic": null },
  { "id": "270", "name": "Ice", "type": null, "alcoholic": null },
  { "id": "271", "name": "Iced tea", "type": null, "alcoholic": null },
  { "id": "272", "name": "Irish cream", "type": "Liqueur", "alcoholic": "Yes" },
  { "id": "273", "name": "Irish Whiskey", "type": "Whiskey", "alcoholic": "Yes" },
  { "id": "275", "name": "Jack Daniels", "type": "Whiskey", "alcoholic": "Yes" },
  { "id": "276", "name": "Jello", "type": null, "alcoholic": null },
  { "id": "277", "name": "Jelly", "type": null, "alcoholic": null },
  { "id": "278", "name": "Jagermeister", "type": "Liqueur", "alcoholic": "Yes" },
  { "id": "279", "name": "Jim Beam", "type": "Whiskey", "alcoholic": "Yes" },
  { "id": "280", "name": "Johnnie Walker", "type": "Whiskey", "alcoholic": "Yes" },
  { "id": "282", "name": "Kahlua", "type": "Liqueur", "alcoholic": "Yes" },
  { "id": "283", "name": "Key Largo Schnapps", "type": "Liqueur", "alcoholic": "Yes" },
  { "id": "284", "name": "Kirschwasser", "type": null, "alcoholic": null },
  { "id": "285", "name": "Kiwi liqueur", "type": "Liqueur", "alcoholic": "Yes" },
  { "id": "286", "name": "Kiwi", "type": null, "alcoholic": null },
  { "id": "287", "name": "Kool-Aid", "type": null, "alcoholic": null },
  { "id": "288", "name": "Kummel", "type": null, "alcoholic": null },
  { "id": "289", "name": "Lager", "type": "Beer", "alcoholic": "Yes" },
  { "id": "293", "name": "Lemon Juice", "type": null, "alcoholic": null },
  { "id": "294", "name": "Lemon Peel", "type": null, "alcoholic": null },
  { "id": "295", "name": "Lemon soda", "type": null, "alcoholic": null },
  { "id": "296", "name": "Lemon vodka", "type": null, "alcoholic": null },
  { "id": "297", "name": "Lemon-lime soda", "type": null, "alcoholic": null },
  { "id": "298", "name": "lemon-lime", "type": null, "alcoholic": null },
  { "id": "299", "name": "lemon", "type": "Fruit", "alcoholic": null },
  { "id": "300", "name": "Lemonade", "type": "Soft Drink", "alcoholic": null },
  { "id": "303", "name": "Licorice Root", "type": null, "alcoholic": null },
  { "id": "304", "name": "Light Cream", "type": null, "alcoholic": null },
  { "id": "305", "name": "Light Rum", "type": "Rum", "alcoholic": "Yes" },
  { "id": "306", "name": "Lillet", "type": null, "alcoholic": null },
  { "id": "307", "name": "Lime juice cordial", "type": null, "alcoholic": null },
  { "id": "308", "name": "Lime Juice", "type": null, "alcoholic": null },
  { "id": "309", "name": "Lime liqueur", "type": "Liqueur", "alcoholic": "Yes" },
  { "id": "310", "name": "Lime Peel", "type": null, "alcoholic": null },
  { "id": "311", "name": "Lime vodka", "type": "Vodka", "alcoholic": "Yes" },
  { "id": "312", "name": "Lime", "type": "Fruit", "alcoholic": null },
  { "id": "313", "name": "Limeade", "type": null, "alcoholic": null },
  { "id": "314", "name": "Madeira", "type": null, "alcoholic": null },
  { "id": "315", "name": "Malibu Rum", "type": "Rum", "alcoholic": "Yes" },
  { "id": "317", "name": "Mandarin", "type": null, "alcoholic": null },
  { "id": "318", "name": "Mandarine napoleon", "type": null, "alcoholic": null },
  { "id": "319", "name": "Mango", "type": null, "alcoholic": null },
  { "id": "320", "name": "Maple syrup", "type": null, "alcoholic": null },
  { "id": "321", "name": "Maraschino cherry juice", "type": null, "alcoholic": null },
  { "id": "322", "name": "Maraschino Cherry", "type": null, "alcoholic": null },
  { "id": "323", "name": "Maraschino Liqueur", "type": "Liqueur", "alcoholic": "Yes" },
  { "id": "324", "name": "Margarita mix", "type": null, "alcoholic": null },
  { "id": "325", "name": "Marjoram leaves", "type": null, "alcoholic": null },
  { "id": "326", "name": "Marshmallows", "type": null, "alcoholic": null },
  { "id": "327", "name": "Maui", "type": null, "alcoholic": null },
  { "id": "328", "name": "Melon Liqueur", "type": "Liqueur", "alcoholic": "Yes" },
  { "id": "329", "name": "Melon Vodka", "type": null, "alcoholic": null },
  { "id": "330", "name": "Mezcal", "type": null, "alcoholic": null },
  { "id": "331", "name": "Midori Melon Liqueur", "type": "Liqueur", "alcoholic": "Yes" },
  { "id": "332", "name": "Midori", "type": "Liqueur", "alcoholic": "Yes" },
  { "id": "333", "name": "Milk", "type": "Drink", "alcoholic": null },
  { "id": "336", "name": "Mint syrup", "type": null, "alcoholic": null },
  { "id": "337", "name": "Mint", "type": "Flower", "alcoholic": null },
  { "id": "338", "name": "Mountain Dew", "type": null, "alcoholic": null },
  { "id": "344", "name": "Nutmeg", "type": null, "alcoholic": null },
  { "id": "346", "name": "Olive Oil", "type": null, "alcoholic": null },
  { "id": "347", "name": "Olive", "type": null, "alcoholic": null },
  { "id": "348", "name": "Onion", "type": null, "alcoholic": null },
  { "id": "350", "name": "Orange Bitters", "type": null, "alcoholic": null },
  { "id": "351", "name": "Orange Curacao", "type": "Liqueur", "alcoholic": "Yes" },
  { "id": "352", "name": "Orange Juice", "type": null, "alcoholic": null },
  { "id": "353", "name": "Orange liqueur", "type": "Liqueur", "alcoholic": "Yes" },
  { "id": "354", "name": "Orange Peel", "type": null, "alcoholic": null },
  { "id": "355", "name": "Orange rum", "type": "Rum", "alcoholic": "Yes" },
  { "id": "356", "name": "Orange Soda", "type": null, "alcoholic": null },
  { "id": "357", "name": "Orange spiral", "type": null, "alcoholic": null },
  { "id": "358", "name": "Orange vodka", "type": "Vodka", "alcoholic": "Yes" },
  { "id": "359", "name": "Orange", "type": "Fruit", "alcoholic": null },
  { "id": "361", "name": "Oreo cookie", "type": null, "alcoholic": null },
  { "id": "362", "name": "Orgeat Syrup", "type": "Syrup", "alcoholic": null },
  { "id": "363", "name": "Ouzo", "type": "Aperitif", "alcoholic": "Yes" },
  { "id": "364", "name": "Oyster Sauce", "type": null, "alcoholic": null },
  { "id": "365", "name": "Papaya juice", "type": null, "alcoholic": null },
  { "id": "366", "name": "Papaya", "type": null, "alcoholic": null },
  { "id": "367", "name": "Parfait amour", "type": null, "alcoholic": null },
  { "id": "372", "name": "Passion fruit juice", "type": null, "alcoholic": null },
  { "id": "373", "name": "Passion fruit syrup", "type": null, "alcoholic": null },
  { "id": "374", "name": "Passoa", "type": "Liqueur", "alcoholic": "Yes" },
  { "id": "375", "name": "Peach brandy", "type": "Brandy", "alcoholic": "Yes" },
  { "id": "376", "name": "Peach juice", "type": null, "alcoholic": null },
  { "id": "377", "name": "Peach liqueur", "type": "Liqueur", "alcoholic": "Yes" },
  { "id": "378", "name": "Peach Nectar", "type": null, "alcoholic": null },
  { "id": "379", "name": "Peach Schnapps", "type": "Liquor", "alcoholic": "Yes" },
  { "id": "380", "name": "Peach Vodka", "type": "Vodka", "alcoholic": "Yes" },
  { "id": "381", "name": "Peach", "type": "Fruit", "alcoholic": null },
  { "id": "382", "name": "Peachtree schnapps", "type": "Liquor", "alcoholic": "Yes" },
  { "id": "383", "name": "Peanut Oil", "type": null, "alcoholic": null },
  { "id": "386", "name": "Pepper", "type": null, "alcoholic": null },
  { "id": "387", "name": "Peppermint extract", "type": null, "alcoholic": null },
  { "id": "388", "name": "Peppermint Schnapps", "type": "Liquor", "alcoholic": "Yes" },
  { "id": "389", "name": "Pepsi Cola", "type": null, "alcoholic": null },
  { "id": "390", "name": "Pernod", "type": null, "alcoholic": null },
  { "id": "391", "name": "Peychaud bitters", "type": null, "alcoholic": null },
  { "id": "392", "name": "Pina colada mix", "type": null, "alcoholic": null },
  { "id": "393", "name": "Pineapple Juice", "type": null, "alcoholic": null },
  { "id": "394", "name": "Pineapple rum", "type": null, "alcoholic": null },
  { "id": "395", "name": "Pineapple vodka", "type": null, "alcoholic": null },
  { "id": "396", "name": "Pineapple-orange-banana juice", "type": null, "alcoholic": null },
  { "id": "397", "name": "Pineapple", "type": "Fruit", "alcoholic": null },
  { "id": "398", "name": "Pink lemonade", "type": null, "alcoholic": null },
  { "id": "399", "name": "Pisang Ambon", "type": null, "alcoholic": null },
  { "id": "400", "name": "Pisco", "type": "Brandy", "alcoholic": "Yes" },
  { "id": "402", "name": "Plain Chocolate", "type": null, "alcoholic": null },
  { "id": "403", "name": "Plain Flour", "type": null, "alcoholic": null },
  { "id": "405", "name": "Plums", "type": null, "alcoholic": null },
  { "id": "406", "name": "Port", "type": "Fortified wine", "alcoholic": "Yes" },
  { "id": "409", "name": "Powdered Sugar", "type": null, "alcoholic": null },
  { "id": "411", "name": "Purple passion", "type": null, "alcoholic": null },
  { "id": "412", "name": "Raisins", "type": null, "alcoholic": null },
  { "id": "413", "name": "Raspberry cordial", "type": null, "alcoholic": null },
  { "id": "414", "name": "Raspberry Jam", "type": null, "alcoholic": null },
  { "id": "415", "name": "Raspberry Juice", "type": null, "alcoholic": null },
  { "id": "416", "name": "Raspberry Liqueur", "type": "Liqueur", "alcoholic": "Yes" },
  { "id": "417", "name": "Raspberry schnapps", "type": "Liquor", "alcoholic": "Yes" },
  { "id": "418", "name": "Raspberry syrup", "type": null, "alcoholic": null },
  { "id": "419", "name": "Raspberry Vodka", "type": "Vodka", "alcoholic": "Yes" },
  { "id": "421", "name": "Red Chile Flakes", "type": null, "alcoholic": null },
  { "id": "422", "name": "Red Chili Flakes", "type": null, "alcoholic": null },
  { "id": "423", "name": "Red Hot Chili Flakes", "type": null, "alcoholic": null },
  { "id": "425", "name": "Red Wine", "type": "Wine", "alcoholic": "Yes" },
  { "id": "426", "name": "Rhubarb", "type": null, "alcoholic": null },
  { "id": "427", "name": "Ricard", "type": "Aperitif", "alcoholic": "Yes" },
  { "id": "429", "name": "Rock Salt", "type": null, "alcoholic": null },
  { "id": "430", "name": "Root beer schnapps", "type": "Liquor", "alcoholic": "Yes" },
  { "id": "431", "name": "Root beer", "type": "Soft Drink", "alcoholic": null },
  { "id": "432", "name": "Roses sweetened lime juice", "type": null, "alcoholic": null },
  { "id": "433", "name": "Rosewater", "type": null, "alcoholic": null },
  { "id": "435", "name": "Rumple Minze", "type": null, "alcoholic": null },
  { "id": "436", "name": "Rye Whiskey", "type": "Whiskey", "alcoholic": "Yes" },
  { "id": "437", "name": "Sake", "type": "Rice wine", "alcoholic": null },
  { "id": "439", "name": "Salt", "type": "Mineral", "alcoholic": null },
  { "id": "440", "name": "Sambuca", "type": "Liqueur", "alcoholic": "Yes" },
  { "id": "441", "name": "Sarsaparilla", "type": null, "alcoholic": null },
  { "id": "442", "name": "Schnapps", "type": "Liquor", "alcoholic": "Yes" },
  { "id": "443", "name": "Schweppes Lemon", "type": null, "alcoholic": null },
  { "id": "444", "name": "Schweppes Russchian", "type": null, "alcoholic": null },
  { "id": "448", "name": "Sherbet", "type": null, "alcoholic": null },
  { "id": "449", "name": "Sherry", "type": "Fortified Wine", "alcoholic": "Yes" },
  { "id": "452", "name": "Sirup of roses", "type": null, "alcoholic": null },
  { "id": "453", "name": "Sloe Gin", "type": "Liqueur", "alcoholic": null },
  { "id": "455", "name": "Soda Water", "type": null, "alcoholic": null },
  { "id": "456", "name": "Sour Apple Pucker", "type": null, "alcoholic": null },
  { "id": "457", "name": "Sour Mix", "type": "Soft Drink", "alcoholic": null },
  { "id": "458", "name": "Southern Comfort", "type": "Liqueur", "alcoholic": "Yes" },
  { "id": "459", "name": "Soy Milk", "type": null, "alcoholic": null },
  { "id": "460", "name": "Soy Sauce", "type": null, "alcoholic": null },
  { "id": "461", "name": "Soya Milk", "type": null, "alcoholic": null },
  { "id": "462", "name": "Soya Sauce", "type": null, "alcoholic": null },
  { "id": "464", "name": "Spiced Rum", "type": null, "alcoholic": null },
  { "id": "466", "name": "Sprite", "type": null, "alcoholic": null },
  { "id": "467", "name": "Squeezed Orange", "type": null, "alcoholic": null },
  { "id": "468", "name": "Squirt", "type": null, "alcoholic": null },
  { "id": "470", "name": "Strawberries", "type": "Fruit", "alcoholic": null },
  { "id": "471", "name": "Strawberry juice", "type": null, "alcoholic": null },
  { "id": "472", "name": "Strawberry liqueur", "type": "Liquor", "alcoholic": "Yes" },
  { "id": "473", "name": "Strawberry Schnapps", "type": "Liquor", "alcoholic": "Yes" },
  { "id": "474", "name": "Strawberry syrup", "type": null, "alcoholic": null },
  { "id": "475", "name": "Sugar Syrup", "type": null, "alcoholic": null },
  { "id": "476", "name": "Sugar", "type": null, "alcoholic": null },
  { "id": "477", "name": "Sunny delight", "type": null, "alcoholic": null },
  { "id": "478", "name": "Surge", "type": null, "alcoholic": null },
  { "id": "479", "name": "Swedish punsch", "type": null, "alcoholic": null },
  { "id": "480", "name": "Sweet and Sour", "type": "Soft Drink", "alcoholic": null },
  { "id": "481", "name": "Sweet Cream", "type": null, "alcoholic": null },
  { "id": "482", "name": "Sweet Vermouth", "type": "Fortified Wine", "alcoholic": "Yes" },
  { "id": "483", "name": "Tabasco Sauce", "type": null, "alcoholic": null },
  { "id": "484", "name": "Tang", "type": null, "alcoholic": null },
  { "id": "485", "name": "Tawny port", "type": "Fortified Wine", "alcoholic": "Yes" },
  { "id": "486", "name": "Tea", "type": null, "alcoholic": null },
  { "id": "487", "name": "Tennessee whiskey", "type": "Whiskey", "alcoholic": "Yes" },
  { "id": "488", "name": "Tequila rose", "type": null, "alcoholic": null },
  { "id": "490", "name": "Tia Maria", "type": null, "alcoholic": null },
  { "id": "492", "name": "Tomato Juice", "type": "Soft Drink", "alcoholic": null },
  { "id": "494", "name": "Tomato", "type": null, "alcoholic": null },
  { "id": "497", "name": "Tonic Water", "type": "Soft Drink", "alcoholic": null },
  { "id": "498", "name": "Triple Sec", "type": "Liqueur", "alcoholic": "Yes" },
  { "id": "499", "name": "Tropicana", "type": null, "alcoholic": null },
  { "id": "500", "name": "Tuaca", "type": null, "alcoholic": null },
  { "id": "502", "name": "Vanilla extract", "type": null, "alcoholic": null },
  { "id": "503", "name": "Vanilla Ice-Cream", "type": null, "alcoholic": null },
  { "id": "504", "name": "Vanilla liqueur", "type": "Liquor", "alcoholic": "Yes" },
  { "id": "505", "name": "Vanilla schnapps", "type": "Liquor", "alcoholic": "Yes" },
  { "id": "506", "name": "Vanilla syrup", "type": null, "alcoholic": null },
  { "id": "507", "name": "Vanilla vodka", "type": "Vodka", "alcoholic": "Yes" },
  { "id": "508", "name": "Vanilla", "type": null, "alcoholic": null },
  { "id": "510", "name": "Vermouth", "type": "Fortified Wine", "alcoholic": "Yes" },
  { "id": "511", "name": "Vinegar", "type": null, "alcoholic": null },
  { "id": "513", "name": "Water", "type": "Water", "alcoholic": null },
  { "id": "514", "name": "Watermelon schnapps", "type": "Liquor", "alcoholic": "Yes" },
  { "id": "515", "name": "Whipped Cream", "type": "Cream", "alcoholic": null },
  { "id": "516", "name": "Whipping Cream", "type": "Cream", "alcoholic": null },
  { "id": "519", "name": "White chocolate liqueur", "type": null, "alcoholic": null },
  { "id": "520", "name": "White Creme de Menthe", "type": null, "alcoholic": null },
  { "id": "521", "name": "White grape juice", "type": null, "alcoholic": null },
  { "id": "522", "name": "White port", "type": "Port", "alcoholic": "Yes" },
  { "id": "523", "name": "White Rum", "type": "Rum", "alcoholic": "Yes" },
  { "id": "524", "name": "White Vinegar", "type": null, "alcoholic": null },
  { "id": "525", "name": "White Wine", "type": "Wine", "alcoholic": "Yes" },
  { "id": "526", "name": "Wild Turkey", "type": "Whisky", "alcoholic": "yes" },
  { "id": "527", "name": "Wildberry schnapps", "type": "Liquor", "alcoholic": "Yes" },
  { "id": "528", "name": "Wine", "type": "Wine", "alcoholic": "Yes" },
  { "id": "529", "name": "Worcestershire Sauce", "type": "Sauce", "alcoholic": null },
  { "id": "530", "name": "Wormwood", "type": null, "alcoholic": null },
  { "id": "531", "name": "Yeast", "type": null, "alcoholic": null },
  { "id": "532", "name": "Yellow Chartreuse", "type": "Liqueur", "alcoholic": "Yes" },
  { "id": "533", "name": "Yoghurt", "type": "Cream", "alcoholic": null },
  { "id": "534", "name": "Yukon Jack", "type": "Liqueur", "alcoholic": "Yes" },
  { "id": "535", "name": "Zima", "type": "Beverage", "alcoholic": "Yes" },
  { "id": "537", "name": "Caramel Sauce", "type": "Sauce", "alcoholic": null },
  { "id": "538", "name": "Chocolate Sauce", "type": "Sauce", "alcoholic": null },
  { "id": "539", "name": "Lillet Blanc", "type": "aperitif", "alcoholic": "Yes" },
  { "id": "540", "name": "Peach Bitters", "type": "bitter", "alcoholic": null },
  { "id": "541", "name": "Mini-snickers bars", "type": "Confectionery\r\n\r\n", "alcoholic": null },
  { "id": "542", "name": "Prosecco", "type": "Wine", "alcoholic": "Yes" },
  { "id": "543", "name": "Salted Chocolate", "type": "Confectionery", "alcoholic": null },
  { "id": "544", "name": "Martini Rosso", "type": "Vermouth", "alcoholic": "Yes" },
  { "id": "545", "name": "Martini Bianco", "type": "Vermouth", "alcoholic": "Yes" },
  { "id": "546", "name": "Martini Extra Dry", "type": "Vermouth", "alcoholic": "Yes" },
  { "id": "547", "name": "Fresh Lime Juice", "type": "Fruit", "alcoholic": null },
  { "id": "548", "name": "Fresh Mint", "type": "Garnish", "alcoholic": null },
  { "id": "549", "name": "Rosemary", "type": "Garnish", "alcoholic": null },
  { "id": "550", "name": "Habanero Peppers", "type": "Garnish", "alcoholic": null },
  { "id": "551", "name": "Ilegal Joven mezcal", "type": "Spirit", "alcoholic": "Yes" },
  { "id": "552", "name": "Elderflower cordial", "type": "Cordial", "alcoholic": null },
  { "id": "553", "name": "Rosso Vermouth", "type": "Fortified Wine", "alcoholic": "Yes" },
  { "id": "554", "name": "Creme de Violette", "type": "Liqueur", "alcoholic": "Yes" },
  { "id": "555", "name": "Cocchi Americano", "type": "Aperitif", "alcoholic": "Yes" },
  { "id": "556", "name": "White Vermouth", "type": "Fortified Wine", "alcoholic": "Yes" },
  { "id": "557", "name": "Dry Curacao", "type": "Liqueur", "alcoholic": "Yes" },
  { "id": "558", "name": "Nocino", "type": "Liqueur", "alcoholic": "Yes" },
  { "id": "559", "name": "Averna", "type": "Liqueur", "alcoholic": "Yes" },
  { "id": "560", "name": "Ramazzotti", "type": "Liqueur", "alcoholic": "Yes" },
  { "id": "561", "name": "Fernet-Branca", "type": "Liqueur", "alcoholic": "Yes" },
  { "id": "562", "name": "Allspice Dram", "type": "Liquer", "alcoholic": "Yes" },
  { "id": "563", "name": "Falernum", "type": "Syrup", "alcoholic": "No" },
  { "id": "564", "name": "Singani", "type": "Liquor", "alcoholic": "Yes" },
  { "id": "565", "name": "Arrack", "type": "Liquor", "alcoholic": "Yes" },
  { "id": "566", "name": "Blackstrap rum", "type": "Rum", "alcoholic": "Yes" },
  { "id": "567", "name": "Ginger Syrup", "type": "Syrup", "alcoholic": "No" },
  { "id": "568", "name": "Honey syrup", "type": "Syrup", "alcoholic": "No" },
  { "id": "569", "name": "Blended Scotch", "type": "Whiskey", "alcoholic": "Yes" },
  { "id": "570", "name": "Islay single malt Scotch", "type": "Whiskey", "alcoholic": "Yes" },
  { "id": "571", "name": "151 proof rum", "type": "Rum", "alcoholic": "Yes" },
  { "id": "572", "name": "7-up", "type": "Soft Drink", "alcoholic": null },
  { "id": "573", "name": "Absinthe", "type": "Spirit", "alcoholic": "Yes" },
  { "id": "574", "name": "Absolut citron", "type": "Vodka", "alcoholic": "Yes" },
  { "id": "575", "name": "Creme de Mure", "type": "Liquor", "alcoholic": "Yes" },
  { "id": "576", "name": "Olive Brine", "type": "Mixer", "alcoholic": "No" },
  { "id": "577", "name": "Pineapple Syrup", "type": "Fruit Juice", "alcoholic": "No" },
  { "id": "578", "name": "St. Germain", "type": "Liquor", "alcoholic": "Yes" },
  { "id": "579", "name": "Lavender", "type": "Flower", "alcoholic": "No" },
  { "id": "600", "name": "Whiskey", "type": "Whisky", "alcoholic": "Yes" },
  { "id": "601", "name": "Whisky", "type": "Whisky", "alcoholic": "Yes" },
  { "id": "602", "name": "Pomegranate juice", "type": "Fruit Juice", "alcoholic": "No" }
]