"""added_favorites_and_methods

Revision ID: 056688d05c7d
Revises: a3ab8f079547
Create Date: 2020-09-09 15:52:51.464828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '056688d05c7d'
down_revision = 'a3ab8f079547'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('drink_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['drink_id'], ['drinks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorites')
    # ### end Alembic commands ###
