"""update_drinks

Revision ID: 70108649ebd9
Revises: 6ecde8946b5d
Create Date: 2020-09-09 14:57:02.736728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70108649ebd9'
down_revision = '6ecde8946b5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drinks', sa.Column('measured_ingrediennts', sa.ARRAY(sa.String(), as_tuple=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drinks', 'measured_ingrediennts')
    # ### end Alembic commands ###
