"""update_drinks_2

Revision ID: a3ab8f079547
Revises: 70108649ebd9
Create Date: 2020-09-09 14:58:17.266870

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a3ab8f079547'
down_revision = '70108649ebd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drinks', sa.Column('measured_ingredients', sa.ARRAY(sa.String(), as_tuple=True), nullable=True))
    op.drop_column('drinks', 'measured_ingrediennts')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drinks', sa.Column('measured_ingrediennts', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.drop_column('drinks', 'measured_ingredients')
    # ### end Alembic commands ###
