"""create_users

Revision ID: d42d0760f54f
Revises: 
Create Date: 2020-09-08 18:23:42.982422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd42d0760f54f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('encrypted_password', sa.LargeBinary(), nullable=False))
    op.add_column('users', sa.Column('first_name', sa.String(length=40), nullable=False))
    op.add_column('users', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(length=40), nullable=False))
    op.drop_constraint('users_username_key', 'users', type_='unique')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(length=40), autoincrement=False, nullable=False))
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'image_url')
    op.drop_column('users', 'first_name')
    op.drop_column('users', 'encrypted_password')
    # ### end Alembic commands ###
