"""remove_image_url_from_users

Revision ID: f213edae4f4f
Revises: f7433f2fdf8b
Create Date: 2020-09-17 11:33:42.672248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f213edae4f4f'
down_revision = 'f7433f2fdf8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'image_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
