"""update_ingredient_model

Revision ID: f7433f2fdf8b
Revises: 056688d05c7d
Create Date: 2020-09-11 13:07:12.788087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7433f2fdf8b'
down_revision = '056688d05c7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingredients', 'alcoholic')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredients', sa.Column('alcoholic', sa.VARCHAR(length=40), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
